name: vertxbus
author: Stephan Wienczny <wienczny@gmail.com>
version: 0.0.1
description: "vertxbus.dart is a Dart package to connect a browser to a Vert.x EventBus"
homepage: "homepage: https://github.com/wienczny/vertxbus.dart"
threadsafe: yes
dependencies:
  uuid: any
  sockjs_client:
      git: git://github.com/nelsonsilva/sockjs-dart-client.git
dev_dependencies:
  unittest: any

